Update frostproxy

diff --git a/usr/bin/frostproxy b/usr/bin/frostproxy
--- a/usr/bin/frostproxy
+++ b/usr/bin/frostproxy
@@ -44,7 +44,7 @@ if [ "$1" == "tunnel" ]; then
             exit 1
         else
             if [ -z "$2" ]; then
-                echo "specify a target: 64.44.56.454:8000"
+                echo "specify a target: 8000"
                 exit 1
             fi
             
@@ -73,6 +73,11 @@ if [ "$1" == "tunnel" ]; then
 
             echo "Creating tunnel..."
             
+
+               echo "Session Status:          Online"
+   echo "Tunnels:                 1"
+   echo "Website Interface:       example.com"
+   echo "Forwarding:              https://example.com -> 64.44.56.454:8000"
             
             #curl -X POST https://frostproxy.com -d '{"domain":"$domain","target":"$target"}'
         fi
@@ -82,13 +87,27 @@ fi
 if [ "$1" == "list" ]; then
     echo "Listing tunnels..."
 
+    configfile='/var/frostproxy/config.cfg'
+    
+    if [ ! -f "${configfile}" ] ; then
+        echo "config file not found, run 'frostproxy config [token]'"
+        exit 1
+    fi
+        
+        source $configfile
+        if [ -f "$token" ]; then
+            echo "token not found, run 'frostproxy config [token]'"
+            exit 1
+        fi
 
 
+response=$(curl -s -i -X POST https://frostproxy.com/api/tunnel/list -d '{ 
+ "ID": "$token"
+}')
 
-   echo "Session Status:          Online"
-   echo "Tunnels:                 1"
-   echo "Website Interface:       example.com"
-   echo "Forwarding:              https://example.com -> 64.44.56.454:8000"
+echo "$response" | grep -o "HTTP/[0-9.]* [0-9]*"
+
+    
 
 
 fi
