Code Overhaul

diff --git a/usr/bin/frostproxy b/usr/bin/frostproxy
--- a/usr/bin/frostproxy
+++ b/usr/bin/frostproxy
@@ -1,30 +1,84 @@
 #!/bin/bash
+
 if [ -z "$1" ]; then
- echo "Enter a command, Use `frostproxy help` for more info"
+    echo "Enter a command, Use 'frostproxy help' for more info"
 fi
 
 if [ "$1" == "help" ]; then
-echo "Usage: frostproxy [command]"
-echo ""
-echo "Commands:"
-echo "  config token [token]"
-echo "  tunnel start  frostproxy tunnel"
-echo "  tunnel stop   frostproxy tunnel"
-echo "  tunnel delete frostproxy tunnel"
+    echo "Usage: frostproxy [command]"
+    echo ""
+    echo "Commands:"
+    echo "  config token [token]"
+    echo "  tunnel target [http:64.44.343.3000] domain [example.com] ssl [true/false]"
+    echo "  list [tunnels]"
+fi
+
+if [ "$1" == "config" ]; then
+    if [ -z "$2" ]; then
+        echo "specify a config: token"
+    fi
+    
+    configfile='/var/frostproxy/config.cfg'
+    
+    if [ ! -f "${configfile}" ] ; then
+        mkdir -p /var/frostproxy/
+        touch $configfile
+        echo "token=\"$2\"" | sudo tee --append $configfile
+    fi
 fi
 
 if [ "$1" == "tunnel" ]; then
-target="$2"
-domain="$3"
+    target="$2"
+    domain="$3"
+    ssl="$4"
+    configfile='/var/frostproxy/config.cfg'
+    
+    if [ ! -f "${configfile}" ] ; then
+        echo "config file not found, run 'frostproxy config [token]'"
+        exit 1
+    else
+        
+        source $configfile
+        if [ -f "$token" ]; then
+            echo "token not found, run 'frostproxy config [token]'"
+            exit 1
+        else
+            if [ -z "$2" ]; then
+                echo "specify a target: 64.44.56.454:8000"
+                exit 1
+            fi
+            
+            if [ -z "$3" ]; then
+                echo "specify a Domain: example.com"
+                exit 1
+            fi
+            
+            if [ -z "$4" ]; then
+                echo "specify a ssl: true or false"
+                exit 1
+            fi
 
-if [ -z "$2" ]; then
-echo "specify a target: 64.44.56.454:8000"
-fi
-if [ -z "$3" ]; then
-echo "specify a Domain: example.com"
+            if [ "$4" != "true" ] && [ "$4" != "false" ]; then
+                echo "specify a ssl: true or false"
+                exit 1
+            fi
+            
+            if [ "$4" == "true" ]; then
+                ssl="true"
+            fi
+            
+            if [ "$4" == "false" ]; then
+                ssl="false"
+            fi
+
+            echo "Creating tunnel..."
+            
+            
+            #curl -X POST https://frostproxy.com -d '{"domain":"$domain","target":"$target"}'
+        fi
+    fi
 fi
 
-echo $target
-echo $domain
-#curl -X POST https://frostproxy.com -d '{\"domain\":\"\$domain\",\"target\":\"\$target\"}'
+if [ "$1" == "list" ]; then
+    echo "Listing tunnels..."
 fi
